services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trends_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trends_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: trends_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trends_db
    volumes:
      - ./app:/code/app 

volumes:
  postgres_data: